// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions
{
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvlZ2InqLkCZOlff5A0v55W4oYbqjqvgY',
    appId: '1:1085329793352:web:d48b452ee40a728d49937d',
    messagingSenderId: '1085329793352',
    projectId: 'ecommerce-1e178',
    authDomain: 'ecommerce-1e178.firebaseapp.com',
    storageBucket: 'ecommerce-1e178.appspot.com',
    measurementId: 'G-88E5FQZBRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwpkoSau1YB7hsLpNKQ1L4QSgCYpnZe9M',
    appId: '1:1085329793352:android:dd862bec29820baf49937d',
    messagingSenderId: '1085329793352',
    projectId: 'ecommerce-1e178',
    storageBucket: 'ecommerce-1e178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD37ihb-Leepue_MHOQ7BxZ4USvBhewGHo',
    appId: '1:1085329793352:ios:535b93bb7bb05cfa49937d',
    messagingSenderId: '1085329793352',
    projectId: 'ecommerce-1e178',
    storageBucket: 'ecommerce-1e178.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD37ihb-Leepue_MHOQ7BxZ4USvBhewGHo',
    appId: '1:1085329793352:ios:535b93bb7bb05cfa49937d',
    messagingSenderId: '1085329793352',
    projectId: 'ecommerce-1e178',
    storageBucket: 'ecommerce-1e178.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvlZ2InqLkCZOlff5A0v55W4oYbqjqvgY',
    appId: '1:1085329793352:web:2c9c862d071fd1a949937d',
    messagingSenderId: '1085329793352',
    projectId: 'ecommerce-1e178',
    authDomain: 'ecommerce-1e178.firebaseapp.com',
    storageBucket: 'ecommerce-1e178.appspot.com',
    measurementId: 'G-V66KZWJFD5',
  );
}
